"""empty message

Revision ID: 484de11b5c5c
Revises: c56828f86242
Create Date: 2020-04-01 12:58:23.462476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484de11b5c5c'
down_revision = 'c56828f86242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('joinDate', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'joinDate')
    # ### end Alembic commands ###
