"""empty message

Revision ID: d8ed8300c03b
Revises: 484de11b5c5c
Create Date: 2020-04-01 13:27:48.236603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8ed8300c03b'
down_revision = '484de11b5c5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('joindate', sa.Date(), nullable=True))
    op.drop_column('user_profile', 'joinDate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('joinDate', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('user_profile', 'joindate')
    # ### end Alembic commands ###
